sudo: false
language: node_js
node_js:
    - stable
    - "0.12"
install:
    - npm install
    - npm install -g mocha
    - npm install -g gulp
    - cd app
    - npm install
script: 
    - mocha
cache:
  directories:
    - node_modules
    - app/node_modules

branches:
    except:
        - feature/command-line-interface 
        - generatorTests/node_modules 