sudo: false
language: node_js
node_js:
    - stable
    - "0.12"
before_install:
    - cd app
    - npm install
install:
    - npm install
    - npm install -g mocha
    - npm install -g gulp
script: 
    - mocha
cache:
  directories:
    - node_modules
    - app/node_modules