sudo: false
language: node_js
node_js:
    - stable
    - "0.12"
install:
    - npm install
    - npm install -g mocha
    - npm install -g gulp
    - cd app
    - mv package.json packageTEMPLATE.json
    - mv ../ci/_packageCi.json package.json
    - npm install
    - rm package.json
    - mv packageTEMPLATE.json package.json
    - cd ..
script: 
    - mocha
cache:
  directories:
    - node_modules
    - app/node_modules