sudo: false
language: node_js
node_js:
    - stable
    - "0.12"
install:
    - npm install
    - npm install -g mocha
    - npm install -g gulp
    - cd app
    - rm package.json && mv _packageTravis.json package.json
    - ls -lG
    - npm install
    - cd ..
script: 
    - mocha
cache:
  directories:
    - node_modules
    - app/node_modules