# branches to build
branches:
  # whitelist
  only:
    - feature/appveyor-build

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

# Test against this version of Node.js
environment:
  nodejs_version: "0.10.30"

# Install scripts. (runs after repo cloning)
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell'
  # batch commands start from cmd:
  - cmd: echo This is batch again
  - cmd: set MY_VAR=12345

# Don't actually build.
build: off
